### ISSUE TITLE
Regarding Compute Resources used for Training and Evaluation.

### ISSUE THREAD

**Issue by Rodrigues-Royston** [fferflo/statewide-visual-geolocalization#1]
Dear Authors, 

Thankyou for your exciting work. 

What is the compute resource (No of. GPUs/V-RAM) that has been used in this work: 
- for training and for testing. 

Best Regards,
Royston

**Comment by fferflo** [comment]
Hi Royston, we used a node with 2x H100 for training and testing, so 160GB of GPU memory. You could scale down the training by reducing for example the image resolutions, model size and batch size in config/main.yaml. Inference with pretrained weights can be done with a batch size of 1, so something like a single 4090 with 24GB would probably be sufficient (although I haven't tried).

**Comment by Rodrigues-Royston** [comment]
Thankyou for your response! 

On your environment of 2 x H100, How long was the training time for this work ?

How many Hours/Days are needed to complete training. 

Your response helps me understand your work better. 

Thankyou for your exciting work!

**Comment by fferflo** [comment]
A single training run takes about 2.5 days in this setup.

Thanks for your interest!
